### ISSUE TITLE
Did all the steps that you described; cmds are still not working.

### ISSUE THREAD

**Issue by bseditor** [abhinaypandey02/bombsquad_chat_commands#1]

**Comment by abhinaypandey02** [comment]
Thank you trying out my commands. Kindly delete the pycache folder in ba directory.

**Comment by bseditor** [comment]
Worked! Gonna add more useful and effective commands? If so, then plz add ASAP.
TQ

**Comment by abhinaypandey02** [comment]
> Worked! Gonna add more useful and effective commands? If so, then plz add ASAP.
> TQ

Glad to know it helped. I would like you to take a look at every command structure and follow the same pattern of classes when adding new cmd. You can create pull requests and I will merge them
