### ISSUE TITLE
Permission 

### ISSUE THREAD

**Issue by ghost** [abhinaypandey02/bombsquad_chat_commands#3]
Hey their !
I would love to use your commands initiator in my scripts , i will leave a credit on README 

Is that okay for you to use your code and modify it !

Actually i am going to distribute scripts 🙃

**Comment by WrenRocks** [comment]
I will rathrr contact on mail !

**Comment by abhinaypandey02** [comment]
As long as you give credits, I dont mind. It is an abandoned project.

**Comment by ghost** [comment]
> As long as you give credits, I dont mind. It is an abandoned project.

**Yeaaa Thanks Man !**
